name: Echo Branch from JSON

on: [push]

jobs:
  echo-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read branch key from JSON
        run: |
          cat file.json
          echo "branch=$(python -c 'import json; f=open("file.json"); branch = json.load(f); print(branch["branch"])')"
          echo "Branch: $branch"
