name: Echo JSON File

on: [push]

jobs:
  echo-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display contents of file.json
        run: |
          cat file.json
          echo "::set-output name=json_contents::$(cat file.json)"

      - name: Print jira 
        run: |
          curl --request GET \
          --url 'https://mrpl272.atlassian.net/rest/api/3/project' \
          --user '${{ secrets.JIRA_USER }}:${{ secrets.JIRA_API_TOKEN}}' \
          --header 'Accept: application/json'
