name: Conditional Job Execution

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run a command
        run: |
          echo "This is job1"
          # Simulate a failure
          exit 1

  job2:
    needs: job1
    if: ${{ needs.job1.result == 'failure' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run a command
        run: echo "This is job2, running because job1 failed"
