name: Run Python Script

on:
  push:
    branches:
      - main

jobs:
  echo-name:
    runs-on: ubuntu-latest
    env:
      NAME: "your_environment_variable_value"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python script
        run: python echo_env.py
