name: Echo Branch from JSON

on: [push]

jobs:
  echo-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read branch key from JSON
        run: |
          branch=$(python -c "
import json, sys
try:
    with open('file.json') as f:
        data = json.load(f)
    print(data['branch'])
except (FileNotFoundError, KeyError) as e:
    print(f'Error: {e}', file=sys.stderr)
    sys.exit(1)
")
          echo "Branch: $branch"
