name: Conditional Job Execution

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      job1_outcome: ${{ steps.check_outcome.outputs.outcome }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run a command
        run: |
          echo "This is job1"
          # Simulate a failure

      - name: Set outcome
        id: check_outcome
        run: echo "::set-output name=outcome::${{ job.status }}"

  check-job1:
    runs-on: ubuntu-latest
    needs: job1
    outputs:
      job1_outcome: ${{ needs.job1.outputs.job1_outcome }}
    steps:
      - name: Set outcome for job2
        run: echo "Outcome of job1 is ${{ needs.job1.outputs.job1_outcome }}"

  job2:
    runs-on: ubuntu-latest
    needs: check-job1
    if: ${{ needs.check-job1.outputs.job1_outcome == 'success' }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Run a command
        run: echo "This is job2, running because job1 failed"
