name: Conditional Payload

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-payload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Read payload.json
      id: read_payload
      run: |
        PAYLOAD=$(cat payload.json)
        echo "PAYLOAD=$PAYLOAD" >> $GITHUB_ENV
        CHECK=$(echo $PAYLOAD | jq -r .check)
        echo "::set-output name=check::$CHECK"
        echo "::set-output name=payload::$PAYLOAD"

    - name: Echo payload if check is yes
      if: steps.read_payload.outputs.check == 'yes'
      run: echo "${{ steps.read_payload.outputs.payload }}"

    - name: Echo no payload if check is no
      if: steps.read_payload.outputs.check != 'yes'
      run: echo "no payload"
