name: Two-Stage Workflow with Artifact

on:
  push:
    branches:
      - main

jobs:
  first_stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate output file
        run: echo "This is a sample output" > output.txt

      - name: Save output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-file
          path: output.txt

  second_stage:
    runs-on: ubuntu-latest
    needs: first_stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: output-file
          path: ./artifact-output

      - name: Use the output
        run: cat ./artifact-output/output.txt
