name: Echo Environment Variable

on: [push]

jobs:
  echo-env-variable:
    runs-on: ubuntu-latest
    env:
      mayur: "Hello from mayur"
    steps:
      - name: Echo the environment variable
        run: echo "name="The value of mayur is:${{ env.mayur }}"" >> GITHUB_ENV

      - name: echo
        run: echo ${{ env.name }}
