name: Conditional Job Execution

on: [push]

jobs:
  check-flag:
    runs-on: ubuntu-latest

    outputs:
      flag: ${{ steps.read_json.outputs.flag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read JSON file and set output
        id: read_json
        run: |
          flag=$(python -c 'import json; f = open("file.json"); data = json.load(f); print(data["flag"])')
          echo "::set-output name=flag::$flag"

  conditional-job:
    runs-on: ubuntu-latest
    needs: check-flag
    if: needs.check-flag.outputs.flag == 'true'

    steps:
      - name: Step 1
        run: echo "Running Step 1 because the flag is true."

      - name: Step 2
        run: echo "Running Step 2 because the flag is true."

      - name: Step 3
        run: echo "Running Step 3 because the flag is true."
