name: Echo JSON File

on: [push]

jobs:
  echo-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Display contents of file.json
        run: |
          cat file.json
          echo "::set-output name=json_contents::$(cat file.json)"

      - name: Print jira 
        run: |
          curl --request GET \
          --url 'https://mrpl272.atlassian.net/rest/api/3/project' \
          --user '${{ secrets.JIRA_USER }}:${{ secrets.JIRA_API_TOKEN}}' \
          --header 'Accept: application/json'

      - name: Create Project
        run: |
          curl --request GET \
          --url 'https://mrpl272.atlassian.net/rest/api/3/project' \
          --user '${{ secrets.JIRA_USER }}:${{ secrets.JIRA_API_TOKEN}}' \
          --header 'Accept: application/json' \
          --data '{
            "assigneeType": "PROJECT_LEAD",
            "avatarId": 10200,
            "categoryId": 10120,
            "description": "Cloud migration initiative",
            "issueSecurityScheme": 10001,
            "key": "EX123456",
            "leadAccountId": "712020:d662bf67-24fd-4405-abf5-a3e80dd4be3c",
            "name": "Example123445677",
            "notificationScheme": 10021,
            "permissionScheme": 10011,
            "projectTemplateKey": "com.atlassian.jira-core-project-templates:jira-core-simplified-process-control",
            "projectTypeKey": "business",
            "url": "http://atlassian.com"
          }'

