name: Run Python Script and Handle Failures

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run fail.py
        id: run_script
        run: |
          python fail.py
        continue-on-error: true  # Allow the job to proceed even if the script fails

      - name: Upload output.json as artifact if script fails
        if: always()  # Run this step no matter what
        uses: actions/upload-artifact@v3
        with:
          name: output-json
          path: output.json

  handle-failure:
    needs: run-python-script
    runs-on: ubuntu-latest

    steps:
      - name: Download output.json artifact
        uses: actions/download-artifact@v3
        with:
          name: output-json

      - name: Echo the contents of output.json
        run: cat output.json
