name: Echo Environment Variable

on: [push]

jobs:
  echo-env-variable:
    runs-on: ubuntu-latest
    env:
      mayur: "Hello from mayur"
    steps:
      - name: Set a new environment variable from the existing one
        run: echo "name=The value of mayur is:${{ env.mayur }}" >> $GITHUB_ENV

      - name: Echo the new environment variable
        run: echo "${{ env.name }}"
