name: Pass Outputs Between Jobs

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      myOutput: ${{ steps.step1.outputs.someValue }}
    steps:
      - name: Run a command to set output
        id: step1
        run: echo "someValue=Hello from job1" >> $GITHUB_OUTOUT
        # Or use:
        # echo "::set-output name=someValue::Hello from job1"

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Use output from job1
        run: echo "The output from job1 is ${{ needs.job1.outputs.myOutput }}"
