name: Echo Branch from JSON

on: [push]

jobs:
  echo-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Read branch key from JSON
        run: |
          branch="mayur223"
          echo "Branch name: $branch"
      
      - name: Configure Git for pushing
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b new_branch
      
      # - name: Create and push new branch
      #   run: |
      #     git checkout -b $branch
      #     git push --set-upstream origin $branch
