name: Two-Stage Workflow

on:
  push:
    branches:
      - main

jobs:
  first_stage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run first stage script
        run: echo "Running first stage"

  second_stage:
    runs-on: ubuntu-latest
    needs: first_stage  # This ensures the second stage runs only if the first stage succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run second stage script
        run: echo "Running second stage"
