name: Create and Get JIRA Project

on:
  push:
    branches:
      - main

jobs:
  create-and-get-jira-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install requests
          # Keep the environment activated for the next steps
          echo 'source $PWD/venv/bin/activate' > activate_venv.sh
          chmod +x activate_venv.sh

      - name: Verify virtual environment
        run: |
          source venv/bin/activate
          python check_venv.py

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # - name: Create JIRA Project
      #   id: create-jira-project
      #   env:
      #     JIRA_USER: ${{ secrets.JIRA_USER }}
      #     JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      #   run: |
      #     python create_jira_project.py
      #   continue-on-error: false

      - name: Get JIRA Project
        env:
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        run: |
          python get_jira_project.py
      
      - name: Find project URL
        run: |
          python find_project_url.py  
